### ISSUE TITLE
ImportError: cannot import name 'VoxelGenerator' from 'spconv.utils' 

### ISSUE THREAD

**Issue by REFRAING** [TRAILab/PDV#20]
when I do python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml
the error like this
/mnt/Anaconda3/envs/PDV/lib/python3.8/runpy.py:127: RuntimeWarning: 'pcdet.datasets.kitti.kitti_dataset' found in sys.modules after import of package 'pcdet.datasets.kitti', but prior to execution of 'pcdet.datasets.kitti.kitti_dataset'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/mnt/wg/PDV/pcdet/datasets/processor/data_processor.py", line 50, in transform_points_to_voxels
    from spconv.utils import VoxelGeneratorV2 as VoxelGenerator
ImportError: cannot import name 'VoxelGeneratorV2' from 'spconv.utils' (/mnt/Anaconda3/envs/PDV/lib/python3.8/site-packages/spconv/utils/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/Anaconda3/envs/PDV/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/Anaconda3/envs/PDV/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/wg/PDV/pcdet/datasets/kitti/kitti_dataset.py", line 501, in <module>
    create_kitti_infos(
  File "/mnt/wg/PDV/pcdet/datasets/kitti/kitti_dataset.py", line 454, in create_kitti_infos
    dataset = KittiDataset(dataset_cfg=dataset_cfg, class_names=class_names, root_path=data_path, training=False)
  File "/mnt/wg/PDV/pcdet/datasets/kitti/kitti_dataset.py", line 23, in __init__
    super().__init__(
  File "/mnt/wg/PDV/pcdet/datasets/dataset.py", line 33, in __init__
    self.data_processor = DataProcessor(
  File "/mnt/wg/PDV/pcdet/datasets/processor/data_processor.py", line 17, in __init__
    cur_processor = getattr(self, cur_cfg.NAME)(config=cur_cfg)
  File "/mnt/wg/PDV/pcdet/datasets/processor/data_processor.py", line 52, in transform_points_to_voxels
    from spconv.utils import VoxelGenerator
ImportError: cannot import name 'VoxelGenerator' from 'spconv.utils' (/mnt/Anaconda3/envs/PDV/lib/python3.8/site-packages/spconv/utils/__init__.py)

**Comment by 1806610292** [comment]
you can try VoxelGeneratorV2 replaced by PointToVoxel
like this
![图片](https://github.com/TRAILab/PDV/assets/55391949/1a4093b6-938f-4a41-ae31-012a031331e2)
reference：
https://github.com/traveller59/spconv/blob/master/docs/SPCONV_2_BREAKING_CHANGEs.md
